#a)
print(2, "кг")
print(13, 17, "\n")

#б)
a = int(input("Введите a: "))
b = int(input("Введите b: "))
print(a, 1)
print(19, b, "\n")

#в)
x = int(input("Введите x: "))
y = int(input("Введите y: "))
print(x, y)
print(5, y)
